package com.dewijones92.ytdlpkt

/** Typed, consumer-facing media metadata — the SDK's abstraction over yt-dlp's VideoInfo. */
data class MediaInfo(
    val id: String?,
    val title: String?,
    val durationSeconds: Int,
    val uploader: String?,
    val webpageUrl: String?,
    val thumbnailUrl: String?,
    val formats: List<MediaFormat>,
    // --- #17 Cycle A: richer metadata (all optional, safe defaults) ---
    val description: String? = null,
    /** View/like/dislike counts; -1 = unknown (NewPipe convention). */
    val viewCount: Long = -1,
    val likeCount: Long = -1,
    val dislikeCount: Long = -1,
    /** yt-dlp `upload_date`, raw "yyyymmdd"; the consumer parses it. */
    val uploadDate: String? = null,
    /** yt-dlp `uploader_id` (e.g. "@handle" or a "UC..." channel id). */
    val uploaderId: String? = null,
    val categories: List<String> = emptyList(),
    val tags: List<String> = emptyList(),
    // --- #17 Cycle B: live + subtitles ---
    val isLive: Boolean = false,
    /** yt-dlp `live_status`: "is_live" / "was_live" / "post_live" / "not_live". */
    val liveStatus: String? = null,
    val subtitles: List<MediaSubtitle> = emptyList(),
) {
    /** Progressive (muxed audio+video) formats, best first by height. */
    val muxedFormats: List<MediaFormat>
        get() = formats.filter { !it.isVideoOnly && !it.isAudioOnly }.sortedByDescending { it.height }

    val audioOnlyFormats: List<MediaFormat> get() = formats.filter { it.isAudioOnly }
    val videoOnlyFormats: List<MediaFormat> get() = formats.filter { it.isVideoOnly }
}

/** A single downloadable representation. */
data class MediaFormat(
    val formatId: String?,
    val ext: String?,
    val width: Int,
    val height: Int,
    val vcodec: String?,
    val acodec: String?,
    /** Average (audio) bitrate, kbps — yt-dlp `abr`. */
    val averageBitrateKbps: Int,
    /** Total bitrate, kbps — yt-dlp `tbr` (used for stream selection/itag bitrate). */
    val totalBitrateKbps: Int,
    /** Audio sample rate in Hz — yt-dlp `asr`. */
    val audioSampleRate: Int,
    /** Frames per second — yt-dlp `fps`. */
    val fps: Int,
    /** yt-dlp `format_note` (e.g. "1080p60", "original", language tag). */
    val formatNote: String?,
    val fileSizeBytes: Long,
    val url: String?,
    // --- #17 Cycle B ---
    /** Audio track language (yt-dlp `language`) for multi-audio/dubbed videos. */
    val language: String? = null,
    /** HLS/DASH manifest URL (yt-dlp `manifest_url`), used for live streams. */
    val manifestUrl: String? = null,
) {
    private fun absent(codec: String?) = codec == null || codec == "none" || codec.isBlank()
    val isAudioOnly: Boolean get() = absent(vcodec) && !absent(acodec)
    val isVideoOnly: Boolean get() = absent(acodec) && !absent(vcodec)
}

/** A subtitle or caption track. */
data class MediaSubtitle(
    val languageCode: String,
    val ext: String?,
    val url: String?,
    val name: String?,
    /** True = auto-generated caption (yt-dlp automatic_captions); false = human subtitle. */
    val autoGenerated: Boolean,
)

/** Streamed progress from [YtdlpKt.download]. */
sealed interface DownloadProgress {
    data class Progress(val percent: Float, val etaSeconds: Long, val line: String) : DownloadProgress
    data class Completed(val exitCode: Int) : DownloadProgress
}

/** Java-friendly progress callback for [YtdlpKt.downloadBlocking]. */
fun interface ProgressListener {
    fun onProgress(percent: Float, etaSeconds: Long, line: String)
}
