package com.dewijones92.ytdlpkt

import com.fasterxml.jackson.databind.DeserializationFeature
import com.fasterxml.jackson.databind.ObjectMapper
import com.yausername.youtubedl_android.mapper.VideoInfo
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Deterministic (no network/device) test of the VideoInfo -> MediaInfo mapping that is the SDK's
 * core typed-layer logic, including audio/video/muxed format classification.
 */
class MappingTest {

    private val mapper = ObjectMapper()
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)

    private val sampleJson = """
        {
          "id": "abc123",
          "title": "Test Video",
          "duration": 212,
          "uploader": "Test Channel",
          "webpage_url": "https://www.youtube.com/watch?v=abc123",
          "thumbnail": "https://i.ytimg.com/abc.jpg",
          "description": "hello world",
          "view_count": 12345,
          "like_count": 678,
          "dislike_count": 9,
          "upload_date": "20240115",
          "uploader_id": "@TestChannel",
          "categories": ["Music"],
          "tags": ["a", "b"],
          "live_status": "not_live",
          "subtitles": {"en": [{"ext": "vtt", "url": "https://s/en.vtt", "name": "English"}]},
          "automatic_captions": {"fr": [{"ext": "vtt", "url": "https://s/fr.vtt", "name": "French from English"}]},
          "formats": [
            {"format_id":"18","ext":"mp4","width":640,"height":360,"vcodec":"avc1.42001E","acodec":"mp4a.40.2","abr":96,"filesize":1048576,"url":"https://x/18"},
            {"format_id":"140","ext":"m4a","width":0,"height":0,"vcodec":"none","acodec":"mp4a.40.2","abr":128,"filesize":524288,"url":"https://x/140","language":"en"},
            {"format_id":"137","ext":"mp4","width":1920,"height":1080,"vcodec":"avc1.640028","acodec":"none","abr":0,"filesize":5242880,"url":"https://x/137"}
          ]
        }
    """.trimIndent()

    private fun parse(): MediaInfo =
        mapper.readValue(sampleJson, VideoInfo::class.java).toMediaInfo()

    @Test
    fun mapsTopLevelFields() {
        val info = parse()
        assertEquals("abc123", info.id)
        assertEquals("Test Video", info.title)
        assertEquals(212, info.durationSeconds)
        assertEquals("Test Channel", info.uploader)
        assertEquals("https://www.youtube.com/watch?v=abc123", info.webpageUrl)
        assertEquals("https://i.ytimg.com/abc.jpg", info.thumbnailUrl)
        assertEquals(3, info.formats.size)
    }

    @Test
    fun classifiesFormats() {
        val info = parse()
        assertEquals(listOf("18"), info.muxedFormats.map { it.formatId })
        assertEquals(listOf("140"), info.audioOnlyFormats.map { it.formatId })
        assertEquals(listOf("137"), info.videoOnlyFormats.map { it.formatId })
    }

    @Test
    fun mapsMetadata() {
        val info = parse()
        assertEquals("hello world", info.description)
        assertEquals(12345L, info.viewCount)
        assertEquals(678L, info.likeCount)
        assertEquals(9L, info.dislikeCount)
        assertEquals("20240115", info.uploadDate)
        assertEquals("@TestChannel", info.uploaderId)
        assertEquals(listOf("Music"), info.categories)
        assertEquals(listOf("a", "b"), info.tags)
    }

    @Test
    fun countsDefaultToUnknownWhenAbsent() {
        val info = mapper.readValue(
            """{"id":"x","title":"t","duration":1,"formats":[]}""", VideoInfo::class.java
        ).toMediaInfo()
        assertEquals(-1L, info.viewCount)
        assertEquals(-1L, info.likeCount)
        assertTrue(info.categories.isEmpty())
    }

    @Test
    fun mapsSubtitlesAndCaptions() {
        val subs = parse().subtitles
        assertEquals(2, subs.size)
        val en = subs.single { it.languageCode == "en" }
        assertEquals("vtt", en.ext)
        assertEquals(false, en.autoGenerated)
        val fr = subs.single { it.languageCode == "fr" }
        assertTrue(fr.autoGenerated)
    }

    @Test
    fun notLiveByDefault() {
        assertEquals(false, parse().isLive)
    }

    @Test
    fun detectsLiveFromStatus() {
        val info = mapper.readValue(
            """{"id":"L","title":"live","duration":0,"live_status":"is_live","formats":[]}""",
            VideoInfo::class.java
        ).toMediaInfo()
        assertTrue(info.isLive)
    }

    @Test
    fun mapsFormatLanguage() {
        assertEquals("en", parse().audioOnlyFormats.single().language)
    }

    @Test
    fun mapsFormatDetails() {
        val muxed = parse().muxedFormats.single()
        assertEquals("mp4", muxed.ext)
        assertEquals(640, muxed.width)
        assertEquals(360, muxed.height)
        assertEquals(96, muxed.averageBitrateKbps)
        assertEquals(1048576L, muxed.fileSizeBytes)
        assertTrue(muxed.url!!.endsWith("/18"))
    }
}
